# Generated by cucumber-sinatra. (2014-10-02 13:52:10 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/beancounter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Beancounter

class BeancounterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BeancounterWorld.new
end
